# H2
spring:
  h2:
  console:
    enabled: true
    path: /h2
  # Datasource
  datasource:
    url: jdbc:h2:file:~/kinder-garden-h2.db
    username: sa
    password: password
    driver-class-name: org.h2.Driver
    jpa:
      hibernate:
        ddl-auto: update
